/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin
 */
public class FrmMenu extends javax.swing.JFrame {
    
    /**
     * Creates new form FrmMenu
     */
    public FrmMenu(String usuario) {
        initComponents();
        txtUsuario.setText(usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        menuRegistrarCasting = new javax.swing.JMenuItem();
        menuRegistrarCliente = new javax.swing.JMenuItem();
        menuRegistrarAgente = new javax.swing.JMenuItem();
        menuRegistrarPerfil = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        menuBuscarCasting = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        menuInformacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/LogoCasting.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 115, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Bienvenido, ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        txtUsuario.setEditable(false);
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 25, 132, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Fondo.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 350, 510));

        fileMenu.setMnemonic('f');
        fileMenu.setText("Registrar");

        menuRegistrarCasting.setMnemonic('o');
        menuRegistrarCasting.setText("Registrar Casting");
        menuRegistrarCasting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarCastingActionPerformed(evt);
            }
        });
        fileMenu.add(menuRegistrarCasting);

        menuRegistrarCliente.setMnemonic('s');
        menuRegistrarCliente.setText("Registrar Cliente");
        menuRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarClienteActionPerformed(evt);
            }
        });
        fileMenu.add(menuRegistrarCliente);

        menuRegistrarAgente.setText("Registrar Agente");
        menuRegistrarAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarAgenteActionPerformed(evt);
            }
        });
        fileMenu.add(menuRegistrarAgente);

        menuRegistrarPerfil.setMnemonic('a');
        menuRegistrarPerfil.setText("Registrar Perfil");
        menuRegistrarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarPerfilActionPerformed(evt);
            }
        });
        fileMenu.add(menuRegistrarPerfil);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Buscar");

        menuBuscarCasting.setMnemonic('t');
        menuBuscarCasting.setText("Buscar Casting");
        menuBuscarCasting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscarCastingActionPerformed(evt);
            }
        });
        editMenu.add(menuBuscarCasting);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");

        menuInformacion.setMnemonic('c');
        menuInformacion.setText("Información");
        menuInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInformacionActionPerformed(evt);
            }
        });
        helpMenu.add(menuInformacion);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInformacionActionPerformed
       JOptionPane.showMessageDialog(this, "Este proyecto fue realizado por \nAlexandra Iveth Rodriguez Castellanos - 229949\nIsaac Castelo Valenzuela - 216823\nSaul Armando Reyna Lopez - 229256\nDiseño de Software", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuInformacionActionPerformed

    private void menuRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarClienteActionPerformed
        FrmRegistrarCliente frmRegcliente = new FrmRegistrarCliente();
        frmRegcliente.setVisible(true);  
    }//GEN-LAST:event_menuRegistrarClienteActionPerformed

    private void menuRegistrarCastingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarCastingActionPerformed
        FrmRegistrarCasting frmRegCasting = new FrmRegistrarCasting();
        frmRegCasting.setVisible(true);
    }//GEN-LAST:event_menuRegistrarCastingActionPerformed

    private void menuRegistrarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarPerfilActionPerformed
        FrmRegistrarPerfil frmRegPerfil = new FrmRegistrarPerfil();
        frmRegPerfil.setVisible(true);
    }//GEN-LAST:event_menuRegistrarPerfilActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       this.dispose();

    }//GEN-LAST:event_btnSalirActionPerformed

    private void menuBuscarCastingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarCastingActionPerformed
        FrmBuscarCasting frmBuscarCasting = new FrmBuscarCasting();
        frmBuscarCasting.setVisible(true);
    }//GEN-LAST:event_menuBuscarCastingActionPerformed

    private void menuRegistrarAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarAgenteActionPerformed
        FrmRegistrarAgente frmRegistrarAgente = new FrmRegistrarAgente();
        frmRegistrarAgente.setVisible(true);
    }//GEN-LAST:event_menuRegistrarAgenteActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuBuscarCasting;
    private javax.swing.JMenuItem menuInformacion;
    private javax.swing.JMenuItem menuRegistrarAgente;
    private javax.swing.JMenuItem menuRegistrarCasting;
    private javax.swing.JMenuItem menuRegistrarCliente;
    private javax.swing.JMenuItem menuRegistrarPerfil;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

}
